micronaut:
  application:
    name: shareholdergame-account

  server:
    port: 8091

  executors:
    scheduled:
      type: scheduled
      core-pool-size: 10

datasources:
  default:
    url: jdbc:mariadb://localhost:3306/shareholdergame
    username: root
    password: 123
    driverClassName: org.mariadb.jdbc.Driver
